### ISSUE TITLE
ur"strings" are syntax errors in Python 3

### ISSUE THREAD

**Issue by cclauss** [future-architect/typescript-guide#14]
__ur"strings"__ are acceptable syntax in Python 2 but are syntax errors in Python 3.

In Python 3, you can have __u"strings"__ or __r"strings"__ but not __"strings"__.

$ __python3 -c "ur'hello'"__  # --> Syntax Error

[flake8](http://flake8.pycqa.org) testing of https://github.com/future-architect/typescript-guide on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./ext/numdoc.py:30:42: E999 SyntaxError: invalid syntax
        self.body.append(ur'第\DUrole{%s}{' % ','.join(classes))
                                         ^
1     E999 SyntaxError: invalid syntax
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by shibukawa** [comment]
I am using Python 3, but I can't reproduce this issue.

**Comment by cclauss** [comment]
`python3 -c "ur'You are?'"`
