### ISSUE TITLE
PDFで「\ 」の一部が「Âa˘」に文字化けしている

### ISSUE THREAD

**Issue by hnakamur** [future-architect/typescript-guide#38]
まず初めに非常に有用なドキュメントを執筆・公開いただきありがとうございます。

PDFを見ていたら以下の画像のように「\ 」の一部が「Âa˘」に文字化けしていました。

![image](https://user-images.githubusercontent.com/19299/82285292-19048880-99d6-11ea-9ba8-cdd50c8fcf30.png)

環境は Windows 10 の Chrome 、 Firefox です。
「\ 」でも文字化けしていないところもあります。法則性があるかいくつかの箇所を見比べてみたのですが残念ながらわかりませんでした。

**Comment by shibukawa** [comment]
Windows10のChromeで表示してみましたが、特に問題なさそうです。いったんクローズします。再現できたら再オープンします。

![image](https://user-images.githubusercontent.com/564612/94043261-9c603b80-fe07-11ea-95d9-d5a51b4bbd2a.png)
