### ISSUE TITLE
as const

### ISSUE THREAD

**Issue by ota-meshi** [future-architect/typescript-guide#48]
https://future-architect.github.io/typescript-guide/typing.html
に追加すると良いと思います。

基本的かと問われるとそうでもないかもしれませんが、定数を定義する際にとてもに便利です。

```ts
const KINDS = ["a", "b", "c"]
// const KINDS: string[]

const KINDS = ["a", "b", "c"] as const
// const KINDS: readonly ["a", "b", "c"]
```

**Comment by shibukawa** [comment]
readonlyが作れるんですね。この使い方は知らなかったです。

オブジェクトの中のキーがstringではなくて、その文字列固有だと示す方法としては紹介しようと思っていて、先だって技術ブログに書いていたのでした。

https://future-architect.github.io/articles/20200730/

**Comment by shibukawa** [comment]
オブジェクトもreadonlyに簡単にできたので一緒に紹介しました

**Comment by shibukawa** [comment]
https://github.com/future-architect/typescript-guide/commit/999ffaeda9690f70c25722832936314bb56fc206
