### ISSUE TITLE
import type

### ISSUE THREAD

**Issue by ota-meshi** [future-architect/typescript-guide#49]
是非この辺りに入れて欲しいです。
https://future-architect.github.io/typescript-guide/module.html#id11

参考に`@typescript-eslint/eslint-plugin@4.x`で追加予定のルール
https://github.com/typescript-eslint/typescript-eslint/blob/v4/packages/eslint-plugin/docs/rules/consistent-type-imports.md

**Comment by shibukawa** [comment]
https://github.com/future-architect/typescript-guide/commit/8d3668c8fde027b6f07fb1354a0f69b1ddf8cc86

これでどうでしょう？

**Comment by shibukawa** [comment]
https://github.com/future-architect/typescript-guide/commit/231691d5cac8eb8ce3d46465730d7e5ce2fa0274

ついかで追記

**Comment by ota-meshi** [comment]
ありがとうございます！

概ねいいのですが、

> 現在リリースされているtypescript-eslintにおいても、\ ``import type``\ を使う方が推奨値としてデフォルト設定されています

の部分は、typescript-eslintの推奨構成ではconsistent-type-importsルールはまだONになってなくて（TS3.7以前もまだサポートしているため推奨構成にはできない）、consistent-type-importsルール単体をユーザーが有効にした場合に``import type``がデフォルトになるだけなので、語弊があると思いました。

**Comment by shibukawa** [comment]
了解です。
