### ISSUE TITLE
前書きの脚注2のtypo

### ISSUE THREAD

**Issue by bubusuke** [future-architect/typescript-guide#51]
現在：
Microsoft社**が**EdgeがChromiumベースにすることが発表され、現在ベータ版が配布されています。

変更後：
Microsoft社**の**EdgeがChromiumベースにすることが発表され、現在ベータ版が配布されています。

**Comment by shibukawa** [comment]
ありがとうございます。もう正式リリースされたので、まるごと書き換えようと思います。
